AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FreshSilver Trip Backend - Chat and RSVP API

Globals:
  Function:
    Timeout: 10
    Runtime: python3.11
    MemorySize: 128
    Environment:
      Variables:
        MESSAGES_TABLE: !Ref MessagesTable
        RSVP_TABLE: !Ref RSVPTable

Resources:
  # DynamoDB Tables
  MessagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: freshsilver-messages
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  RSVPTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: freshsilver-rsvp
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: eventId
          AttributeType: S
        - AttributeName: visitorId
          AttributeType: S
      KeySchema:
        - AttributeName: eventId
          KeyType: HASH
        - AttributeName: visitorId
          KeyType: RANGE

  # Lambda Function
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: freshsilver-api
      CodeUri: src/
      Handler: handler.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MessagesTable
        - DynamoDBCrudPolicy:
            TableName: !Ref RSVPTable
      Events:
        GetMessages:
          Type: HttpApi
          Properties:
            Path: /messages
            Method: GET
            ApiId: !Ref HttpApi
        PostMessage:
          Type: HttpApi
          Properties:
            Path: /messages
            Method: POST
            ApiId: !Ref HttpApi
        GetRSVP:
          Type: HttpApi
          Properties:
            Path: /rsvp/{eventId}
            Method: GET
            ApiId: !Ref HttpApi
        PostRSVP:
          Type: HttpApi
          Properties:
            Path: /rsvp/{eventId}
            Method: POST
            ApiId: !Ref HttpApi
        DeleteRSVP:
          Type: HttpApi
          Properties:
            Path: /rsvp/{eventId}/{visitorId}
            Method: DELETE
            ApiId: !Ref HttpApi

  # HTTP API (cheaper than REST API)
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: prod
      CorsConfiguration:
        AllowOrigins:
          - "https://freshsilver.net"
          - "http://localhost:5173"
          - "http://localhost:5174"
        AllowMethods:
          - GET
          - POST
          - DELETE
          - OPTIONS
        AllowHeaders:
          - Content-Type
          - X-Visitor-Id
        MaxAge: 86400

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
  MessagesTableName:
    Description: DynamoDB Messages Table
    Value: !Ref MessagesTable
  RSVPTableName:
    Description: DynamoDB RSVP Table
    Value: !Ref RSVPTable
